### ISSUE TITLE
This user ID is reserved by an application service.

### ISSUE THREAD

**Issue by almereyda** [tulir/mautrix-telegram#242]
After following the [Docker installation instructions](https://github.com/tulir/mautrix-telegram/wiki/Bridge-setup-with-Docker), copying `registration.yaml` as `mautrix.yaml` to `synapse`'s `appservices` directory, restarting it, and running the container for the third time, I get the following error message:

```
mautrix_1    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
mautrix_1    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
mautrix_1    | [2018-10-30 02:05:24,937] [DEBUG@mau.init] Initializing mautrix-telegram 0.4.0+dev
mautrix_1    | [2018-10-30 02:05:25,007] [DEBUG@mau.init] Initialization complete, running startup actions
mautrix_1    | [2018-10-30 02:05:25,007] [DEBUG@mau.as.api] POST /register {"username": "telegrambot"} as user No identity
mautrix_1    | [2018-10-30 02:05:25,066] [ERROR@mau.as.intent] Failed to register @telegrambot:matrix.allmende.io!
mautrix_1    | Traceback (most recent call last):
mautrix_1    |   File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 896, in ensure_registered
mautrix_1    |     await self._register()
mautrix_1    |   File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
mautrix_1    |     errcode=errcode, message=message)
mautrix_1    | mautrix_appservice.errors.MatrixRequestError: 400: {"errcode":"M_EXCLUSIVE","error":"This user ID is reserved by an application service."}
mautrix_1    | [2018-10-30 02:05:25,067] [DEBUG@mau.as.api] PUT /profile/@telegrambot:matrix.allmende.io/displayname {"displayname": "Allmende Telegram bridge"} as user No identity
mautrix_1    | Traceback (most recent call last):
mautrix_1    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
mautrix_1    |     "__main__", mod_spec)
mautrix_1    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
mautrix_1    |     exec(code, run_globals)
mautrix_1    |   File "/opt/mautrix-telegram/mautrix_telegram/__main__.py", line 135, in <module>
mautrix_1    |     loop.run_until_complete(asyncio.gather(*startup_actions, loop=loop))
mautrix_1    |   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
mautrix_1    |     return future.result()
mautrix_1    |   File "/opt/mautrix-telegram/mautrix_telegram/matrix.py", line 46, in init_as_bot
mautrix_1    |     displayname if displayname != "remove" else "")
mautrix_1    |   File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 338, in set_display_name
mautrix_1    |     await self.client.request("PUT", f"/profile/{self.mxid}/displayname", content)
mautrix_1    |   File "/usr/lib/python3.6/site-packages/mautrix_appservice/intent_api.py", line 136, in _send
mautrix_1    |     errcode=errcode, message=message)
mautrix_1    | mautrix_appservice.errors.MatrixRequestError: 404: {"errcode":"M_UNKNOWN","error":"No row found"}
```

**Comment by almereyda** [comment]
The associated `registration.yaml` looks like:

```
id: telegram
as_token: <redacted>
hs_token: <redacted>
namespaces:
    users:
    - exclusive: true
      regex: '@telegram_.+:matrix.allmende.io'
    aliases:
    - exclusive: true
      regex: '#telegram_.+:matrix.allmende.io'
url: http://mautrix:8080
sender_localpart: telegrambot
rate_limited: false
```

I'm really just following the instructions here. Which part am I missing?

**Comment by almereyda** [comment]
I can now confirm that all new user registrations are being denied and blocked with the same error message:

> # This user ID is reserved by an application service.

https://riot.allmende.io/

![bildschirmfoto von 2018-11-01 20-11-49](https://user-images.githubusercontent.com/1645308/47873828-8495fd80-de12-11e8-9904-bdb1076402ff.png)

**Comment by almereyda** [comment]
Oh thank you, there may be a point here. I didn't look into this. Why does Dimension require this by default?

```
id: dimension-zFwkTWIYiPOn99BP0qg2VgBGb
url: https://connect.allmende.io/_matrix/appservice/r0
as_token: <redacted>
hs_token: <redacted>
sender_localpart: .
namespaces:
  users:
    - exclusive: true
      regex: '@..*'
  aliases: []
  rooms: []

```

Will push this to upstream, and close here.
