### ISSUE TITLE
Add myroomnick support for message_formats

### ISSUE THREAD

**Issue by zouppen** [tulir/mautrix-telegram#604]
We are using channel specific nicknames in radio amateur channel where we have ham radio callsigns as nicknames.

If users set their own channel-specific nickname using `/myroomnick`, it is not used when bridging messages to Telegram. The current supported are according to the documentation (example-config.yaml):

```
    # The formats to use when sending messages to Telegram via the relay bot.
    # Text msgtypes (m.text, m.notice and m.emote) support HTML, media msgtypes don't.
    #
    # Available variables:
    #   $sender_displayname - The display name of the sender (e.g. Example User)
    #   $sender_username    - The username (Matrix ID localpart) of the sender (e.g. exampleuser)
    #   $sender_mxid        - The Matrix ID of the sender (e.g. @exampleuser:example.com)
    #   $message            - The message content
    message_formats:
        m.text: "<b>$sender_displayname</b>: $message"
        m.notice: "<b>$sender_displayname</b>: $message"
        ...
```

Would it possible to add support for `$sender_roomnick` to `message_formats`?
